apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend-store
  namespace: devconnect
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Authenticate vault via Kubernetes ServiceAccount token
        kubernetes:
          mountPath: "kubernetes"
          role: "devconnect-role"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: devconnect
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-store
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: 'Owner'
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: devconnect/database
        property: MONGODB_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: devconnect/backend
        property: JWT_SECRET
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: devconnect/database
        property: ROOT_USER
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: devconnect/database
        property: ROOT_PASSWORD
    - secretKey: MONGO_INITDB_DATABASE
      remoteRef:
        key: devconnect/database
        property: DATABASE_NAME
