apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-lb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
spec:
  type: LoadBalancer
  ports:
    - name: http-query
      port: 80
      targetPort: 16686 # Default Jaeger UI Port
      protocol: TCP
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
