apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devconnect-stage
  namespace: argocd
  annotations:
    # Argo CD Image Updater Configurations
    argocd-image-updater.argoproj.io/image-list: backend=programmingprobhet/devconnect-backend, frontend=programmingprobhet/devconnect-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^stage-.*
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^stage-.*
    # Write back changes directly to the Git repository
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git_branch: main
spec:
  project: devconnect-project
  source:
    repoURL: 'https://github.com/ProgrammingProphet/DevConnect-DevOps.git'
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devconnect-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
