---
- name: Update apt repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common utilities
  apt:
    name:
      - git
      - curl
      - jq
      - vim
      - unzip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
    state: present
