apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: devconnect-prod
type: Opaque
data:
  # echo -n "your-super-secret-jwt-key" | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==
  # echo -n "admin" | base64
  MONGO_USER: YWRtaW4=
  # echo -n "password123" | base64
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=
